baseURL      = 'https://duckpuppy.com/'
languageCode = 'en-us'
title        = '# cat /proc/brain'

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  description = "Dev diaries, technical musings, and occasional pop culture thoughts"
  author      = "duckpuppy"

  # Theme settings
  defaultTheme                   = "auto" # auto, light, dark
  disableThemeToggle             = false
  ShowReadingTime                = true
  ShowShareButtons               = true
  ShowPostNavLinks               = true
  ShowBreadCrumbs                = true
  ShowCodeCopyButtons            = true
  ShowWordCount                  = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc                     = true
  disableSpecial1stPost          = false
  disableScrollToTop             = false
  comments                       = false
  hidemeta                       = false
  hideSummary                    = false
  showtoc                        = true
  tocopen                        = false

  [params.homeInfoParams]
    Title = "cat /proc/brain"
    Content = """
Welcome to my digital brain dump. Here you'll find:
- **Dev Diaries**: Notes from personal projects and experiments
- **Technical Posts**: Thoughts on software development, infrastructure, and tools
- **Pop Culture**: Occasional tangents about movies, games, and other interests
"""

  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/duckpuppy"

  [[params.socialIcons]]
    name = "rss"
    url  = "/index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 10

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 20

  [[menu.main]]
    identifier = "archives"
    name       = "Archives"
    url        = "/archives/"
    weight     = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences    = true
    guessSyntax   = false
    lineNos       = true
    noClasses     = false
    style         = "monokai"
